# Generated by Django 4.2.2 on 2023-06-26 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=10, unique=True, verbose_name='Внешний id')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок')),
                ('min_price_in_euro', models.IntegerField(verbose_name='Минимальная стоимость, €')),
                ('max_price_in_euro', models.IntegerField(verbose_name='Максимальная стоимость, €')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Широта WGS 84, градусы')),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Долгота WGS 84, градусы')),
                ('il', models.IntegerField(verbose_name='Il')),
                ('ilce', models.IntegerField(verbose_name='Ilce')),
                ('mahalle', models.IntegerField(verbose_name='Mahalle')),
                ('deal_types', models.CharField(max_length=100, verbose_name='Тип сделки')),
                ('min_area_in_sq_meters', models.IntegerField(blank=True, null=True, verbose_name='Минимальная площадь, м²')),
                ('max_area_in_sq_meters', models.IntegerField(blank=True, null=True, verbose_name='Максимальная площадь, м²')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('building_start', models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата начала строительства')),
                ('building_end', models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата окончания строительства')),
                ('blocks_number', models.IntegerField(blank=True, null=True, verbose_name='Количество блоков (корпусов)')),
                ('storeys_number', models.IntegerField(blank=True, null=True, verbose_name='Количество этажей')),
                ('sea_distance', models.IntegerField(blank=True, null=True, verbose_name='Расстояние до моря, м')),
                ('center_distance', models.IntegerField(blank=True, null=True, verbose_name='Расстояние до центра, м')),
                ('airport_distance', models.IntegerField(blank=True, null=True, verbose_name='Расстояние до аэропорта')),
                ('url', models.CharField(max_length=1000, verbose_name='URL-ссылка')),
                ('sold', models.BooleanField(default=False, verbose_name='Продано?')),
                ('priority_number', models.IntegerField(verbose_name='Приоритет')),
                ('vip', models.BooleanField(default=False, verbose_name='Вип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='Feature')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='PropertyLayouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_name', models.CharField(max_length=100, verbose_name='Layout')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='PropertyPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование партнера')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сайт партнера')),
                ('image', models.CharField(blank=True, max_length=150, null=True, verbose_name='Логотип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='Тип недвижимости')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='PropertyManagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя менеджера')),
                ('url_whatsapp', models.CharField(max_length=100, verbose_name='Ссылка на whatsapp')),
                ('url_telegram', models.CharField(blank=True, max_length=100, verbose_name='Ссылка на telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('partner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='testdb.propertypartners')),
            ],
            options={
                'verbose_name_plural': 'Managers',
            },
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=200, verbose_name='URL картинки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('properties', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='testdb.property')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='testdb.propertyfeatures', verbose_name='features'),
        ),
        migrations.AddField(
            model_name='property',
            name='layouts',
            field=models.ManyToManyField(blank=True, null=True, to='testdb.propertylayouts', verbose_name='layouts'),
        ),
        migrations.AddField(
            model_name='property',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testdb.propertymanagers', verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='property',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testdb.propertypartners', verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testdb.propertytype', verbose_name='Тип недвижимости'),
        ),
    ]
